### ISSUE TITLE
[FEATURE] Allow n_ctx Customization for model text inference

### ISSUE THREAD

**Issue by corbin-hayden13** [NexaAI/nexa-sdk#109]
### Feature Description

The default maximum context window for all text models is hard-coded at 2048 tokens, but many models have a context window much larger than this.  I would like to have an argument added to `nexa run [model_path]` called `--context_maximum_length` or something similar that allows the user to define their own maximum context window.

I implemented the change myself, I'd be more than happy to make a pull request for the feature.  Here's how I implemented it:

**nexa/cli/entry.py**:
*Adding the argument*
```python
text_group.add_argument("-cm", "--context_maximum", type=int, default=2048, help="Maximum context length of the model you're using")
```

**nexa/gguf/nexa_inference_text.py**:
*Adding the argument*
```python
parser.add_argument(
        "-cm",
        "--context_maximum",
        type=int,
        default=2048,
        help="Maximum context length of the model you're using"
    )
```
*Replacing hard-coded 2048 when initializing Llama in* `self._load_model()`
```python
n_ctx=self.params.get("context_maximum", 2048),
```

**nexa/constants.py**
*Add "context_maximum" to the* `DEFAULT_TEXT_GEN_PARAMS` *which is updated by initializing a* `NexaTextInference` *object*
```python
DEFAULT_TEXT_GEN_PARAMS = {
    "temperature": 0.7,
    "max_new_tokens": 2048,
    "context_maximum": 2048,
    "top_k": 50,
    "top_p": 1.0,
}
```

These are the three files and all changes that need to be made to implement this feature for text models.  I did not look into the other models, but I'm sure exploration of any context limits would reveal a fix for them as well.

**Comment by zhiyuan8** [comment]
@corbin-hayden13 Thanks for this feature request, we will include this `n_ctx` for both LLM/VLM inference engine and API. It will be rolled out in our next release.

**Comment by corbin-hayden13** [comment]
Awesome, I'll look forward to it!

**Comment by zhycheng614** [comment]
@corbin-hayden13 Thank you so much for your feature request and your solution provided. It is applied in #155 to both text inference and VLM inference, which made our sdk more robust. 
Thanks again for your patience and contributions. This feature should be out in our next release.

**Comment by zhycheng614** [comment]
https://github.com/NexaAI/nexa-sdk/releases/tag/v0.0.8.7
