### ISSUE TITLE
[QUESTION] How to set local path?

### ISSUE THREAD

**Issue by nmandic78** [NexaAI/nexa-sdk#142]
I have folder full of GGUF models. How can I run server or cli with path to model in my folder? I don't want to download them again. 
Beside that, is it possible to set path to custom local folder so I can list my previously downloaded models with nexa list?

### OS

Ubuntu

### Nexa SDK Version

0.0.8.6

**Comment by zhiyuan8** [comment]
We will support this option in our next release, now we support using our default downloadable path or huggingface url.

**Comment by zhycheng614** [comment]
I regret to say the running for the models from your local path is currently not directly supported. However, currently there are several alternative ways to reach similar effects:
1. (Recommended) Upload your .gguf models to our on-device AI model hub (https://nexaai.com/models) in your personal repo. Then you will be able to run it on nexa-sdk with command `nexa run <username>/<repo_name>:<tag_name>`. Note that one model tag should exactly correspond to one quantization version of your model. 
2. Use our python interface (import python package).

The feature to support local running will be supported very soon in our next release. Please keep yourself updated.

**Comment by nmandic78** [comment]
Thank you for answer. I will use python interface for now. It would be drop-in replacement for my other code relying on OpenAI compatible endpoint using your server, but this is also viable.

**Comment by zhycheng614** [comment]
Hi,

I'm delighted to inform you that your feature request has been fulfilled in #151 . Now you only need to wait for our new release (0.0.8.7), for all use cases: cli, python interface, server, streamlit, and for all inference types.

Note that to run model with local path in cli, -lp (--local_path) and -mt (--model_type) are both required. Refer to our updated cli readme for detailed instructions: [CLI.md](https://github.com/NexaAI/nexa-sdk/blob/main/CLI.md)

The command should be like:
`nexa run <local_path> -lp -mt NLP`

Thank you.

**Comment by nmandic78** [comment]
Fantastic! You guys are great. Thank you.

**Comment by zhycheng614** [comment]
https://github.com/NexaAI/nexa-sdk/releases/tag/v0.0.8.7

**Comment by ethernidee** [comment]
Does not work anymore

**Comment by wereretot** [comment]
> Does not work anymore

I've noticed as well, it is really inefficient to have to download a model you already have locally just because this program doesn't like its peas with its porridge.

**Comment by ethernidee** [comment]
I agree. I have a 1 TB carefully crafted collection of models and it's just impossible to download and cache each model for each engine.
