### ISSUE TITLE
[QUESTION] Is there any way to set the models download location?

### ISSUE THREAD

**Issue by hammer-ai** [NexaAI/nexa-sdk#168]
### Question or Issue

Hi there, is there any way to set the models download location? Thank you!

**Comment by zhycheng614** [comment]
Hi,

I'm happy to answer your question!

Currently, setting the model download location is not explicitly supported.

However, you can
1. Go to ~/.cache/nexa/hub/official to find the downloaded models
2. Make a feature request so we can support customized download path in the future releases

Thank you,

Perry
Nexa AI

**Comment by hammer-ai** [comment]
Thanks! Closing this and re-opened it as a featured request here: https://github.com/NexaAI/nexa-sdk/issues/173
