### ISSUE TITLE
[FEATURE] Specify models download location

### ISSUE THREAD

**Issue by hammer-ai** [NexaAI/nexa-sdk#173]
### Feature Description

Hi there, it would be awesome if we can specify the models download location. Thank you!

### Similar Features or References

https://github.com/NexaAI/nexa-sdk/issues/168

**Comment by Davidqian123** [comment]
Thank you for the feature request! It will be supported in the next release.

**Comment by zhycheng614** [comment]
Hi,

I'm delighted to inform you that your feature request has just been fulfilled in #200 . Now you can use a -o \<path\> argument to customize your download location with `nexa pull`.

Best,
Perry
Nexa AI
