### ISSUE TITLE
[FEATURE] LoRA support for image generation

### ISSUE THREAD

**Issue by hammer-ai** [NexaAI/nexa-sdk#174]
### Feature Description

Hi there, it would be awesome if we can add LoRA support for image generation. Thank you!

**Comment by Davidqian123** [comment]
Actually we have LoRA in both text generation and image generation.
For text generation, add `--lora_path path/to/lora_file`. For image generation, add `--lora_dir path/to/lora_dir`. https://docs.nexa.ai/sdk/cli-reference
We will upload more LoRA models to our modelhub in the  future and make LoRA experience more smoothly in Nexa SDK. Any LoRA models you are interested in?

**Comment by hammer-ai** [comment]
Oh, awesome, thank you! I'm particularly interested in being able to tell users "download any LoRA from CivitAI and you can use it". So as long as they are all supported, I don't particularly need them available on the modelhub (though having Flux and SD variants on the modelhub is really useful!). Thanks!
