### ISSUE TITLE
[QUESTION] Console prompts for manual input instead of using provided string

### ISSUE THREAD

**Issue by fbesoainp** [NexaAI/nexa-sdk#181]
### Question or Issue

Hi,

I’m using the Nexa SDK to query a LLM model through Nexa’s gguf TextInterface. When I try to use the `create_completion` method, instead of using the string I pass as input, the console prompts me to manually type the input.

Below is my implementation:

```
from nexa.gguf import NexaTextInference

class NexaaiIntegration:
    _instance: NexaaiIntegration | None = None
    _lock: Lock = Lock()
    inference: NexaTextInference | None = None

    def __new__(cls, model_path="llama3-uncensored") -> NexaaiIntegration:
        with cls._lock:
            if cls._instance is None:
                cls._instance = super(NexaaiIntegration, cls).__new__(cls)
                cls._instance.inference = NexaTextInference(
                    model_path=model_path,
                    local_path=None,
                    stop_words=[],
                    temperature=0.7,
                    max_new_tokens=512,
                    top_k=50,
                    top_p=0.9,
                    profiling=True,
                )
                cls._instance.inference.run()
                cls._instance.inference.run_streamlit(model_path)
            return cls._instance

    def create_text_completion(
        self, message: str
    ):
        return self._instance.inference.create_completion(message)
```

And I’m calling it in a FastAPI route:

```
@router.post("/", status_code=HTTPStatus.CREATED)
def read_inquiry(body: InquiryRequest) -> JSONResponse:
    nexa = NexaaiIntegration()
    completion = nexa.create_text_completion(body.message)
    print(completion)
    return JSONResponse(content={"message": completion})
```

However, when I send a POST request, I get this prompted in the console:
```
INFO:     127.0.0.1:58663 - "POST /inquiry HTTP/1.1" 307 Temporary Redirect
Model Llama3-8B-Lexi-Uncensored:q4_K_M already exists at /Users/fbesoain/.cache/nexa/hub/official/Llama3-8B-Lexi-Uncensored/q4_K_M.gguf
>>> Send a message ... (type "/exit" to quit)
```

Instead of processing the input message from the POST request, it prompts me to enter a message manually in the console. How can I modify my implementation so that it uses the string provided in body.message as input instead of prompting me for manual input?

### OS

macOS

### Python Version

3.11.7

### Nexa SDK Version

0.0.8.5

### GPU (if using one)

Apple M1 Pro

**Comment by Davidqian123** [comment]
Thank you for your information! 
Upgrade to the newest version (0.0.9.0) of nexa sdk
`CMAKE_ARGS="-DGGML_METAL=ON -DSD_METAL=ON" pip install -U nexaai --prefer-binary --index-url https://nexaai.github.io/nexa-sdk/whl/metal --extra-index-url https://pypi.org/simple --no-cache-dir`
Remove this two lines and it should work, already tested on my mac
`cls._instance.inference.run()`
`cls._instance.inference.run_streamlit(model_path)`

**Comment by fbesoainp** [comment]
That worked perfectly, thank you!
