### ISSUE TITLE
[QUESTION] Omnivision: Does token compression method results in an inference speedup?

### ISSUE THREAD

**Issue by sguru-sam** [NexaAI/nexa-sdk#261]
### Question or Issue

I read the interesting blog about omnivision: https://nexa.ai/blogs/omni-vision
I have one question on 9x Tokens Reduction through Token Compression.

From the architecture and following writeup `We developed a reshaping mechanism in the projection stage that transforms image embeddings from [batch_size, 729, hidden_size] to [batch_size, 81, hidden_size*9]`: it seems the number of floating points of visual tokens will remain the same. 

I was wondering if this Token Compression method will result in reduction in inference time. Can you please provide an elaborate answer. 

Thanks.

**Comment by zhiyuan8** [comment]
@sguru-sam We have reshape

**Comment by alexchen4ai** [comment]
> ### Question or Issue
> I read the interesting blog about omnivision: https://nexa.ai/blogs/omni-vision I have one question on 9x Tokens Reduction through Token Compression.
> 
> From the architecture and following writeup `We developed a reshaping mechanism in the projection stage that transforms image embeddings from [batch_size, 729, hidden_size] to [batch_size, 81, hidden_size*9]`: it seems the number of floating points of visual tokens will remain the same.
> 
> I was wondering if this Token Compression method will result in reduction in inference time. Can you please provide an elaborate answer.
> 
> Thanks.
> 
> ### OS
> _No response_
> 
> ### Python Version
> _No response_
> 
> ### Nexa SDK Version
> _No response_
> 
> ### GPU (if using one)
> _No response_

Hi, it will reduce inference time! So, the computation of the visual encoder and projection part is the same. However, you still need the computation from the decoder part, the language backbone. Previously, your language model needs to handle 729 tokens, now it becomes 81! Thus, it will greatly reduce the complexity for the decoder part, which is also the main computation time.
