### ISSUE TITLE
OSError: [WinError -529697949] Windows Error 0xe06d7363 when inference

### ISSUE THREAD

**Issue by catzqaz** [NexaAI/nexa-sdk#265]
>>> nexa run omnivision
>>> C:\Users\admin\Desktop\pingpong.webp
>>> what are they doing
2024-11-21 14:11:12,821 - ERROR -
Error during audio generation: [WinError -529697949] Windows Error 0xe06d7363
Traceback (most recent call last):
  File "nexa\gguf\nexa_inference_vlm_omni.py", line 115, in run
  File "nexa\gguf\nexa_inference_vlm_omni.py", line 128, in inference
  File "nexa\gguf\llama\omni_vlm_cpp.py", line 67, in omnivlm_inference
OSError: [WinError -529697949] Windows Error 0xe06d7363

seems _load_shared_library omni_vlm_wrapper_shared.dll error

### OS

windows11

### Nexa SDK Version

0.0.9.2

### GPU (if using one)

rtx 4090

**Comment by zhiyuan8** [comment]
It is strange to see audio processing here
```
Error during audio generation: [WinError -529697949] Windows Error 0xe06d7363
```
Also, would you please try a jpeg or png format image?

**Comment by catzqaz** [comment]
> It is strange to see audio processing here
> 
> ```
> Error during audio generation: [WinError -529697949] Windows Error 0xe06d7363
> ```
> 
> Also, would you please try a jpeg or png format image?

my problem.
now I use nexa run omnivision -st, it works fine.
