### ISSUE TITLE
[BUG] Omnivision produces random outputs

### ISSUE THREAD

**Issue by TyraVex** [NexaAI/nexa-sdk#267]
### Issue Description

Hello, I am trying to use OmniVision, without success

### Steps to Reproduce

```
>>> banana.png
>>> In which waste category should the item shown in the image go?
  
Response: asso 1.


>>> banana.png
>>> In which waste category should the item shown in the image go? 1.paper 2.plastic 3.glass 4.metal 5.organic 6.waste 7.special 8.mixed
  
Response: /
```

![banana](https://github.com/user-attachments/assets/a34a8bf9-ee8e-48bb-a13b-62f8d4022d4c)

### OS

Arch Linux

### Python Version

Python 3.12.7

### Nexa SDK Version

Latest commit 5538d0b2ab0144c1ba76c473b8341f15c60aba19 

### GPU (if using one)

CPU inference

**Comment by zhiyuan8** [comment]
@TyraVex We are continuously training this model with SFT & DPO technics, and will provide the updated model checkpoint soon

**Comment by ghost** [comment]
> @TyraVex We are continuously training this model with SFT & DPO technics, and will provide the updated model checkpoint soon

![Screenshot_2024-11-21-20-19-57-862_org mozilla firefox](https://github.com/user-attachments/assets/dbfb97c1-b3a2-41b6-8ba0-54d952b902b8)

This is not a quality issue, there is something clearly wrong in my setup. I cloned the repo, updated tbe submodules, and ran `pip install -e .` The hf space behaves way differently

**Comment by zhiyuan8** [comment]
@TyraVex Thank you for pointing this out, while we are checking out ggml implementation, would you please check if you are using quantized verison? We hosted full precision version in fp16 on huggingface while the nexa sdk supports q4_0 and 8_0. You can find it by typing
```
nexa list
```

**Comment by ghost** [comment]
I confirm I am using FP16 precision for the text and for the vision model:

Here's `$HOME/.cache/nexa/hub/model_list.json`:
```
{
  "omnivision:model-fp16": {
    "type": "gguf",
    "location": "/home/user/.cache/nexa/hub/official/omnivision/model-fp16.gguf",
    "run_type": "Multimodal"
  },
  "omnivision:projector-fp16": {
    "type": "gguf",
    "location": "/home/user/.cache/nexa/hub/official/omnivision/projector-fp16.gguf",
    "run_type": "Multimodal"
  }
}
```

And `nexa list`
```
+-----------------------+------+------------+----------------------------------------------------------------+
| Model Name            | Type | Run Type   | Location                                                       |
+-----------------------+------+------------+----------------------------------------------------------------+
| omnivision:model-fp16 | gguf | Multimodal | /home/user/.cache/nexa/hub/official/omnivision/model-fp16.gguf |
+-----------------------+------+------------+----------------------------------------------------------------+
```

**Comment by ghost** [comment]
I tried on another Linux machine, updated and running x86_64.

Steps:
```
git clone https://github.com/NexaAI/nexa-sdk
cd nexa-sdk
git submodule update --init --recursive
python -m venv venv
. venv/bin/activate
pip install -e .
nexa run omnivision
```

Output:
```
(venv) ~/downloads/nexa-sdk nexa run omnivision
Downloading omnivision/model-fp16.gguf...
model-fp16.gguf: 100%|███████████████████████| 948M/948M [04:26<00:00, 3.73MB/s]
Successfully downloaded omnivision/model-fp16.gguf to /home/user/.cache/nexa/hub/official/omnivision/model-fp16.gguf
Successfully pulled model omnivision:model-fp16 to /home/user/.cache/nexa/hub/official/omnivision/model-fp16.gguf, run_type: Multimodal
Downloading omnivision/projector-fp16.gguf...
projector-fp16.gguf: 100%|███████████████████| 913M/913M [04:08<00:00, 3.85MB/s]
Successfully downloaded omnivision/projector-fp16.gguf to /home/user/.cache/nexa/hub/official/omnivision/projector-fp16.gguf
Successfully pulled model omnivision:projector-fp16 to /home/user/.cache/nexa/hub/official/omnivision/projector-fp16.gguf, run_type: Multimodal
Using omni-vlm-version: vlm-81-instruct
>>> /home/user/downloads/banana.png
>>> Describe the image
  
Response: The image features a wooden table with a close-up view of a partially eaten banana that has been split in half. The banana peel is yellow, and the remaining fruit is mostly white. The table appears to be made of wood, and the close-up shot emphasizes the banana's unusual split shape.

>>> /home/user/downloads/banana.png
>>> In which waste category should the item shown in the image go? 1.paper 2.plastic 3.glass 4.metal 5.organic 6.waste 7.special 8.mixed
  
Response: /

>>> /home/user/downloads/banana.png
>>> In which waste category should the item shown in the image go?
  
Response: asso 1.

>>> /home/user/downloads/banana.png
>>> What is the object shown in the picture? If trashed, should it go into the paper bin, the platic bin, or the organic bin?
  
Response:  0.50998888888889 0.41875 0.177222222222222 0.177222222222222 0.177222222222222 0.177222222222222 0.177222222222222 0.177222222222222 0.177222222222222 0.177222222222222 0.177222222222222 0.177222222222222 0.177222222222222 0.177222222222222 0.177222222222
```

~~Nvm it is working, it's simply not able to anything else than describing an image.
It's understandable for a 0.5B model.~~

Nevermind the nevermind:

![Screenshot_2024-11-22-09-08-14-978_org mozilla firefox-edit](https://github.com/user-attachments/assets/165ecd92-74d5-4bb0-942b-79c2254bba8f)

It works online with the new weights.
Can't wait to have it locally!

**Comment by alexchen4ai** [comment]
> In which waste category should the item shown in the image go?

https://huggingface.co/spaces/NexaAIDev/omnivlm-dpo-demo

Hi, you can have a test of the same question on our huggingface space. We have updated the model, and it works well for this case. Also, we found GGUF lose some precision, and we are working on it.

**Comment by Davidqian123** [comment]
Try our latest version (v0.0.9.4) of nexa-sdk, it should work well with the updated model

**Comment by alexchen4ai** [comment]
> ### Issue Description
> Hello, I am trying to use OmniVision, without success
> 
> ### Steps to Reproduce
> ```
> >>> banana.png
> >>> In which waste category should the item shown in the image go?
>   
> Response: asso 1.
> 
> 
> >>> banana.png
> >>> In which waste category should the item shown in the image go? 1.paper 2.plastic 3.glass 4.metal 5.organic 6.waste 7.special 8.mixed
>   
> Response: /
> ```
> 
> ![banana](https://private-user-images.githubusercontent.com/34800546/388468870-a34a8bf9-ee8e-48bb-a13b-62f8d4022d4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzk2MDgsIm5iZiI6MTczMjMzOTMwOCwicGF0aCI6Ii8zNDgwMDU0Ni8zODg0Njg4NzAtYTM0YThiZjktZWU4ZS00OGJiLWExM2ItNjJmOGQ0MDIyZDRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA1MjE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNTU5NzUzNmU5ZDU4YThhODViODkxYmNjMmU1YzZjYTZhY2IyODBlYmY3MTllZjE2OGViMzBkOTdjOTI3NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W8fxqaEBFK3t6UsZoiqT16HROdqFaJvjMn41olJTQpM)
> 
> ### OS
> Arch Linux
> 
> ### Python Version
> Python 3.12.7
> 
> ### Nexa SDK Version
> Latest commit [5538d0b](https://github.com/NexaAI/nexa-sdk/commit/5538d0b2ab0144c1ba76c473b8341f15c60aba19)
> 
> ### GPU (if using one)
> CPU inference

https://huggingface.co/spaces/NexaAIDev/omnivlm-dpo-demo

You can also consider to try our huggingface space.

**Comment by ghost** [comment]
```
Downloading omnivision/model-fp16.gguf...
model-fp16.gguf: 100%|████████████████████████| 948M/948M [00:07<00:00, 131MB/s]
Successfully downloaded omnivision/model-fp16.gguf to /home/user/.cache/nexa/hub/official/omnivision/model-fp16.gguf
Successfully pulled model omnivision:model-fp16 to /home/user/.cache/nexa/hub/official/omnivision/model-fp16.gguf, run_type: Multimodal
Downloading omnivision/projector-fp16.gguf...
projector-fp16.gguf: 100%|████████████████████| 913M/913M [00:06<00:00, 142MB/s]
Successfully downloaded omnivision/projector-fp16.gguf to /home/user/.cache/nexa/hub/official/omnivision/projector-fp16.gguf
Successfully pulled model omnivision:projector-fp16 to /home/user/.cache/nexa/hub/official/omnivision/projector-fp16.gguf, run_type: Multimodal
Using omni-vlm-version: vlm-81-instruct
>>>> /home/user/other/quickshare/banana.png
>>> In which waste category should the item shown in the image go?
  
Response: The item shown in the image, which is a peeled banana, should go into the waste category of food. Bananas are typically classified as a food item, and they are often consumed as a snack or eaten as a part of a meal.
```

Thank you very much!

**Comment by ghost** [comment]
I declared victory too early :(

```
>>> /home/user/other/quickshare/banana.png
>>> in which waste category should the item shown in the image go?
please answer with the correct number:
 
1) paper
2) plastic
3) glass
4) metal
5) organic
6) waste
7) special
8) mixed
  
Response: The item shown in the image, which is a peeled banana, should be classified as a "paper" waste category. This classification is based on the fact that the banana peel is peeled, which is a common practice when disposing of unwanted items.
```

On the hugging face space:
```
The correct answer to the question is:1) paper
```
