### ISSUE TITLE
[QUESTION] qwen2audio link?

### ISSUE THREAD

**Issue by Hotohori** [NexaAI/nexa-sdk#290]
### Question or Issue

The wrong link for qwen2audio inside README.md lead to https://www.nexaai.com/qnguyen3/nanoLLaVA/gguf-fp16/readme

### OS

-

### Python Version

-

### Nexa SDK Version

-

### GPU (if using one)

-

**Comment by unseenmars** [comment]
Fixed. Thanks for the heads-up.
