### ISSUE TITLE
[License] Update OuteTTS 500M to correct license

### ISSUE THREAD

**Issue by Kostis-S-Z** [NexaAI/nexa-sdk#309]
On your [website](https://nexa.ai/OuteAI/OuteTTS-0.2-500M/gguf-q4_K_M/readme) you have OuteTTS-0.2-500M under CC-BY-4.0 while its under CC BY NC 4.0 ([source](https://huggingface.co/OuteAI/OuteTTS-0.2-500M))

**Comment by Davidqian123** [comment]
Thank you for your reminder, will update soon!
